# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 807b12db24778788c093ca55812a67c3b5b96b1fef332f1c76279fef6ecaabbca5907f00cd9590ad81c88feaf2528884436cf994809b16a76521f56873cb00c6

test:
  secret_key_base: 3ddec6487049e0a7ceb8be5d26920ee75c3b864906b17f769cdcd9211fad106886ed86b7e0d43c4ad24edea66c40234a7083b1ada5e9c35c4df9c082e3db21d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
